In [1]:
import numpy as np

In [2]:
from read_plot import *

# Create dataframe

In [3]:
# Define a date range
dates = pd.date_range('2010-01-22', '2010-01-26')

# Choose stock symbols to read
symbols = ['GOOG', 'IBM', 'GLD']
    
# Get stock data
df1 = get_data(symbols, dates)

In [4]:
df1

SPY    GOOG     IBM     GLD
2010-01-26  95.770236  542.42  119.85  107.56
2010-01-25  96.173257  540.00  120.20  107.48
2010-01-22  95.682624  550.01  119.61  107.17

# Lesson

## Relationship To Pandas

Converting pd dataframe into numpy array

In [5]:
nd1 = df1.values

In [6]:
nd1

array([[  95.770236,  542.42    ,  119.85    ,  107.56    ],
       [  96.173257,  540.      ,  120.2     ,  107.48    ],
       [  95.682624,  550.01    ,  119.61    ,  107.17    ]])

In [7]:
nd1[0:3, 1:3]

array([[ 542.42,  119.85],
       [ 540.  ,  120.2 ],
       [ 550.01,  119.61]])

## Creating numpy array

Default number is floating

In [8]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [9]:
np.empty((5,4))

array([[  0.00000000e+000,   0.00000000e+000,   5.43472210e-323,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          8.37170573e-144],
       [  0.00000000e+000,   2.68156175e+154,   7.12420702e-091,
          6.70848183e+170]])

In [11]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [12]:
np.random.randint(10)

9

In [13]:
np.random.randint(0, 10, size=5)

array([8, 4, 6, 4, 5])

In [14]:
np.random.randint(0, 10, size=(2,3))

array([[1, 6, 5],
       [0, 2, 3]])

In [24]:
nd2 = np.random.random((5,4))

## Array attributes

- ```numpy.ndarray.shape```: Dimensions (height, width, ...)
- ```numpy.ndarray.ndim```: No. of dimensions = len(shape)
- ```numpy.ndarray.size```: Total number of elements
- ```numpy.ndarray.dtype```: Datatype

In [25]:
nd2.shape

(5, 4)

In [26]:
nd2.shape[0]

5

In [27]:
nd2.shape[1]

4

In [28]:
nd2.size

20

In [29]:
nd2.ndim

2

In [30]:
len(nd2.shape)

2

In [31]:
nd2.dtype

dtype('float64')

## Operations on array

- ```numpy.sum```: Sum of elements - along rows, columns or all
- ```numpy.min```, ```numpy.max```, ```numpy.mean```: Simple statistics

In [39]:
np.random.seed(693) #seed the random number generator 
a = np.random.randint(0, 10, (5,4))
a

array([[2, 0, 5, 1],
       [1, 3, 4, 4],
       [9, 2, 9, 1],
       [9, 3, 7, 5],
       [4, 7, 0, 3]])

In [42]:
a.sum(axis=0) #sum of each column

array([25, 15, 25, 14])

In [43]:
a.sum(axis=1) #sum of each row

array([ 8, 12, 21, 24, 14])

In [44]:
a.min(axis=0)

array([1, 0, 0, 1])

## Locate maximum value

In [50]:
a.argmax(axis=0)

array([2, 4, 2, 3])

In [51]:
np.argmax(a)

8

## Modify array element

In [53]:
nd1

array([[  95.770236,  542.42    ,  119.85    ,  107.56    ],
       [  96.173257,  540.      ,  120.2     ,  107.48    ],
       [  95.682624,  550.01    ,  119.61    ,  107.17    ]])

In [55]:
nd1[:,1] = 1

In [56]:
nd1

array([[  95.770236,    1.      ,  119.85    ,  107.56    ],
       [  96.173257,    1.      ,  120.2     ,  107.48    ],
       [  95.682624,    1.      ,  119.61    ,  107.17    ]])

In [57]:
nd1[:,1] = [1, 2, 3]

In [58]:
nd1

array([[  95.770236,    1.      ,  119.85    ,  107.56    ],
       [  96.173257,    2.      ,  120.2     ,  107.48    ],
       [  95.682624,    3.      ,  119.61    ,  107.17    ]])

## Indexing An Array With Another Array

In [59]:
a = np.random.rand(5)

In [60]:
a

array([ 0.31127579,  0.62872047,  0.07569968,  0.54876981,  0.53860522])

In [61]:
indices = np.array([1, 1, 2, 3])

In [62]:
print(a[indices])

[ 0.62872047  0.62872047  0.07569968  0.54876981]


## Boolean Or "Mask" Index Arrays

In [63]:
a = a[a<a.mean()]

In [64]:
a

array([ 0.31127579,  0.07569968])

## Arithmetic Operations

[Reference](http://docs.scipy.org/doc/numpy/reference/routines.math.html#arithmetic-operations)

- ```numpy.add```: Element-wise addition, same as + operator
- ```numpy.subtract```: Element-wise subtraction, same as -
- ```numpy.multiply```: Element-wise multiplication, same as *
- ```numpy.divide```: Element-wise division, same as /
- ```numpy.dot```: Dot product (1D arrays), matrix multiplication (2D)