This is a variation of cross-validation used in time series data. This function is already implemented by [Sklearn](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html).

In [8]:
from sklearn.model_selection import TimeSeriesSplit
import numpy as np
import pandas as pd

In [2]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])

In [3]:
X.shape, y.shape

((6, 2), (6,))

In [4]:
tscv = TimeSeriesSplit(n_splits=3)

In [5]:
tscv

TimeSeriesSplit(n_splits=3)

In [6]:
# if the input is numpy array
for train, test in tscv.split(X):
    print("%s %s" % (train, test))

[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]


In [10]:
X = pd.DataFrame(X)
y = pd.DataFrame(y)

In [14]:
X

0  1
0  1  2
1  3  4
2  1  2
3  3  4
4  1  2
5  3  4

In [21]:
# if the input is dataframe
for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X.iloc[train_index[-1]], X.iloc[test_index]
    print(X_train)
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [0 1 2] TEST: [3]
0    1
1    2
Name: 2, dtype: int64


KeyError: '[1 2] not in index'

In [ ]:
X