This is a variation of cross-validation used in time series data. This function is already implemented by [Sklearn](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html).

In [3]:
from sklearn.model_selection import TimeSeriesSplit
import numpy as np

In [4]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])

In [5]:
X.shape, y.shape

((6, 2), (6,))

In [6]:
cv = TimeSeriesSplit(n_splits=3)

In [7]:
cv

TimeSeriesSplit(n_splits=3)

In [9]:
for train, test in cv.split(X):
    print("%s %s" % (train, test))

[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]
